### PR TITLE
filling in and submitting form and showing the values as default #144

### PR DESCRIPTION
**Pull request by maatata**
Hi Kevin

I raised an issue and had a solution for it. You requested me to make a pull request maybe this helps everyone.

Here is the changes I have done to make it work.

The way to use it is as follow:

imagine the form is submitted by client. 

in PHP we can grab all the submitted values with $_POST

here is what I do to use this new functionality

<?php $defaultValues = json_encode($_POST); ?>

<script>
$(function(){
            var defaultValues = $.parseJSON(\''.$defaultValues.'\');
            var formContainer = document.getElementById("rendered-form");
            formRenderOpts = {
                container: $("form", formContainer),
                defaultValues: defaultValues
            };
            $(".render-form").formRender(formRenderOpts);
});
</script>

and imagine this is the form already built:

<div class="render-form" style="display:none!important;">
    <form-template>
        <fields>
            <field class="checkbox" label="Checkbox" name="checkbox-1462192519387" type="checkbox"></field>
            <field class="checkbox-group" label="Checkbox Group" name="checkbox-group-1462192523296" type="checkbox-group">
                <option value="option-1">Option 1</option>
                <option value="option-2">Option 2</option>
            </field>
            <field class="form-control calendar" label="Date Field" name="date-1462192527829" type="date"></field>
            <field class="form-control file-input" label="File Upload" name="file-1462192532058" type="file"></field>
            <field class="header" label="Header" type="header" subtype="h1"></field>
            <field class="paragraph" label="Paragraph" type="paragraph" subtype="p"></field>
            <field class="radio-group" label="Radio Group" name="radio-group-1462192543741" type="radio-group">
                <option value="option-1">Option 1</option>
                <option value="option-2">Option 2</option>
            </field>
            <field class="form-control select" label="Select" name="select-1462192546811" type="select">
                <option value="option-1">Option 1</option>
                <option value="option-2">Option 2</option>
            </field>
            <field class="form-control text-input" label="Text Field" name="text-1462192548821" type="text" subtype="text"></field>
            <field class="form-control text-area" label="Text Area" name="textarea-1462192552061" type="textarea"></field>
            <field class="btn btn-info button-input" label="Button" name="button-1462192648526" type="button" subtype="submit"></field>
        </fields>
    </form-template>
</div>

<div id="rendered-form">
    <form method="post" action="<?php echo $modulelink ?>&action=add">
    </form>
</div>

I hope this helps and if not a good way of doing it let me know please so I work on it.

Thanks

### CODE REVIEW

**Comment by kevinchappell** [comment]
I like where this is going and have made some changes that resolve some formatting issues and error when there are no `defaultValues` configured. Could you open PR against development branch so we can collaborate on those changes?

**Comment by PMtr** [comment]
Hello,
Great job, forms are fine.
I'm probably too novice in jquery.
But the main goal of a form is to be posted and eventually checked, so, have you examples for accessing values of the different fields when rendering and how to post the rendered forms (in javascript) ?

**Comment by m-bagheri** [comment]
Hi Kevinchappell,

Sorry mate for the delay responding to your message. I am currently super busy that's why I haven't had time to respond. I will do soon. thanks

**Comment by m-bagheri** [comment]
Hi PMtr,

Well I am currently super busy. Are you trying to integrate this within a web application?
To pass default values to form renderer you would need to have each field name as the array key and the value of that field as the value.

as an example you could pass like follow:

in PHP: 

$defaultValues = array(
'customfield1-name'=>'customfield1-value',
'customfield2-name'=>'customfield2-value',
'customfield3-name'=>'customfield3-value',
'customfield4-name'=>'customfield4-value'
);

$defaultValues = json_encode($defaultValues);

in frontend html or php create a variable in <script> tag called defaultValues and set the value as $defaultValues like below:

var defaultValues = <?php echo $defaultValues; ?>

then if you load that page you see all the fields are filled in with the values saved.

I hope this helps

**Comment by kevinchappell** [comment]
I think the functionality of this PR has some cross-over with the json feature in development and the `value` attribute that was added a few versions back. Closing for now but please reopen if im missing the mark.

**Pull request closed without merging**
