### PR TITLE
Custom element rendering multiple times

### PR DESCRIPTION
**Pull request by divyesh-aks**
In form-builder.min.js file you can find changes between line#2289-2295 with comment // change for custom element render

### CODE REVIEW

**Comment by divyesh-aks** [comment]
In form-builder.min.js file you can find changes between line#2289-2295 with comment "// change for custom element render"

**Comment by kevinchappell** [comment]
Can you make you changes in `src/`? I'm not able to see what was changed other than the new html file

**Comment by divyesh-aks** [comment]
Changes directly made in demo/assets/js/form-builder.min.js after beautifying js file.

**Comment by divyesh-aks** [comment]
Hi Kevin,

Changes added to `src`.

**Comment by kevinchappell** [comment]
Thank you, I was about to merge but need to remove the changes from demo/assets/js/form-builder.min.js. This will be generated during release and there will be a conflict.

**Comment by divyesh-aks** [comment]
Hello Kevin, 
I have reverted all changes made in demo/assets/js/form-builder.min.js
Thanks

**Comment by kevinchappell** [comment]
Truly sorry so much time has passed before getting to merging this. Thank you for the contribution.

**Comment by divyesh-aks** [comment]
Thank kevin 👍

**Comment by divyesh-aks** [comment]
What option need to set so custom element rendering works fine?

**Pull request merged**
