### PR TITLE
bootstrap grid "t.classList is undefined" fixed

### PR DESCRIPTION
**Pull request by suleymantasci**

### CODE REVIEW

**Comment by Goddard** [comment]
I am still getting this error on Firefox.

I add an autocomplete field then click the pencil icon add any additional class other than form-control such as row-1 and then close the edit screen by clicking the pencil icon.  You should get the error.

**Comment by suleymantasci** [comment]
@Goddard  I guess Kevin didn't merge my edit. Get the formbuilder from github. Then replace src/js/layout.js with the one here. 
https://github.com/kevinchappell/formBuilder/blob/17e52f0350fcde02e6915b9e16cb30ef6e92d96a/src/js/layout.js
Get build and use form-builder.js and form-render.js files prepared for you. It will not be a problem.

**Comment by kevinchappell** [comment]
@suleymantasci sorry just getting to this. Can you explain how this error occurs with steps to reproduce? I don't quite understand the problem or why it only occurs with those fields.

**Comment by Jojoshua** [comment]
Try this again with the latest version

**Comment by kevinchappell** [comment]
@suleymantasci thanks for submitting this PR. I wish I had got to it sooner but the issue seems resolved as I'm not able to reproduce the error. @lucasnetau is having a look as well, if the problem is gone PR will be closed.

**Comment by lucasnetau** [comment]
As it stands, this error cannot occur anymore due to the additional check for field.classList existence before calling field.classList.remove()

**Comment by lucasnetau** [comment]
Alternate PR opened https://github.com/kevinchappell/formBuilder/pull/1412, closing this in favour of the new PR

**Pull request closed without merging**
