### PR TITLE
Implemented saving method toJSON

### PR DESCRIPTION
**Pull request by Yc-Chen**
related to issue #184

### CODE REVIEW

**Comment by kevinchappell** [comment]
Looking good. going to test now.

**Comment by kevinchappell** [comment]
I am having difficulty getting this to work. Can you include the `getJSON` function you mentioned in #184 and possibly provide an example on using `toJSON`?

**Comment by Yc-Chen** [comment]
I have created a demo under the 'json' branch here:
[https://github.com/Yc-Chen/formBuilder/tree/json/demo-json](https://github.com/Yc-Chen/formBuilder/tree/json/demo-json)
I do not know how to use gulp so I directly edited the built js file. But I commented 'REVIEW' where I made changes. 
I also implemented the `getJSON` method but it is not working.

A screenshot to show the output json file looks like this:
screenshot - 20-07-16 - 17 36 56

**Comment by kevinchappell** [comment]
Thats a good start. The field objects are missing the name data which may be why its not working but I'll look closer to be sure. Also we'll need a trimming function to keep remove empty properties. There is already something like this in formBuilder called `_helpers.trimAttrs()` but it should really be renamed `trimObj`.

Good work

**Comment by Yc-Chen** [comment]
I figured out what went wrong. Now my master branch should contain the correct `to-json.js` to generate json string. How does this work? Should I send another pull request?

**Comment by kevinchappell** [comment]
Excellent, I'll check it out. You should only need to rebase against master to catch your feature branch up with changes since opening the pr.

**Comment by kevinchappell** [comment]
Looks like you got the branch caught but I'm still getting an error: `getJSON is undefined`.

**Comment by Yc-Chen** [comment]
I tried to break the entry of `getJSON` but it still doesn't work. So I tried to get where `getJSON` is referred. 

`grep -rl "getJSON" .` shows:
`./demo/assets/js/form-builder.min.js`
`./demo/assets/js/form-builder.min.js.map`

`grep -rl "getXML" .` shows:
`./demo/assets/js/form-builder.min.js.map`
`./dist/form-builder.js`
`./src/js/form-builder.js`

It looks something wrong with gulp. But for myself, I included the files in the src folder to the html and it works fine...

**Comment by kevinchappell** [comment]
@Yc-Chen I really appreciate the effort that went into this PR but was not able to get it fully working. It did function as guidance and inspiration for #237 and for that I- am I'm sure a good number of formBuilder users, are very grateful. 

JSON Support is now part of formBuilder as of #237 .

**Pull request closed without merging**
