### PR TITLE
Hotfix: getData

### LINKED ISSUE #462: formBuilder.actions.getData() is not working
formBuilder.actions.getData() is not working with new update

     http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/getData/

    form-builder.js?779f:1427 Uncaught TypeError: Cannot read property 'prepData' of undefined
    at Object.json (eval at <anonymous> (form-builder.js:436), <anonymous>:1338:41)
    at Object.getData (eval at <anonymous> (form-builder.js:436), <anonymous>:1342:24)
    at HTMLButtonElement.<anonymous> (pen.js:10)

### PR DESCRIPTION
**Pull request by kevinchappell**
Resolves #462

### CODE REVIEW

**Comment by ziarno** [comment]
It seems this fix is not on npm yet

**Comment by kevinchappell** [comment]
@ziarno `getFormData` may have a different name in the minified version. Be sure `actions.getData` is being called after formBuilder is fully initialized.

**Comment by ziarno** [comment]
I reverted to 2.1.0 and my app works ;)
yes, I know that the name might change, but in the minified version of 2.1.0 that name is there. Also, this name is in the latest version in minified file on github! It's just not there when I do `npm install formBuilder` - strange.

**Comment by parthik-quebix** [comment]
demoFirst.js:261 Uncaught TypeError: fb.actions.getData is not a function
    at demoFirst.js:261:35
    at Array.map (<anonymous>)
    at HTMLButtonElement.<anonymous> (demoFirst.js:260:37)
    at HTMLButtonElement.dispatch (vendor.js:5206:27)
    at HTMLButtonElement.elemData.handle (vendor.js:5014:28)
(anonymous) @ demoFirst.js:261
(anonymous) @ demoFirst.js:260
dispatch @ vendor.js:5206
elemData.handle @ vendor.js:5014

**Pull request merged**
