### PR TITLE
Solved bug, adding two fields containing typeUserAttr, the typeUserAt…

### PR DESCRIPTION
**Pull request by gimigliano**
Solved bug, adding two fields containing typeUserAttr, the typeUserAttr of the second field had the values of the typeUserAttr of the previous field

### CODE REVIEW

**Comment by kevinchappell** [comment]
This looks good to me but can you describe the steps to reproduce the error? I tried a few combinations but was not able to produce the error.

**Comment by gimigliano** [comment]
In this fiddler https://jsfiddle.net/ab5a3sd0/1/ try to add a new text field.
You'll find the "myfield" attribute valorized with the value of the formData text field

**Comment by kevinchappell** [comment]
@gimigliano thanks, thats clears it up.

**Comment by kevinchappell** [comment]
@gimigliano btw, youre killing it on these PRs, you even made it on the top contributors, good work :tada:

**Comment by gimigliano** [comment]
Wow,  what have I win?

**Comment by kevinchappell** [comment]
@gimigliano :100: internet points :smile:

**Comment by gimigliano** [comment]
oh so I'm happy. Just remember to add typeUserAttr in README.md  options

**Comment by kevinchappell** [comment]
knew i was forgetting something... Should be there now.

**Pull request merged**
