### PR TITLE
disableInjectedStyle option

### LINKED ISSUE #443: Requiring external module babel-register
I'm using window 10, I have downloaded project from git as zip, and run 
npm install
npm start
```
D:\JqueryFormbuilder\formBuilder-master>npm start

> formBuilder@2.1.2 start D:\JqueryFormbuilder\formBuilder-master
> node ./node_modules/gulp/bin/gulp.js
[10:24:49] Requiring external module babel-register
[10:24:53] Using gulpfile D:\JqueryFormbuilder\formBuilder-master\gulpfile.babel.js
[10:24:53] Starting 'devJS'...
[10:24:54] Finished 'devJS' after 810 ms
[10:24:54] Starting 'devCss'...
[10:24:55] Finished 'devCss' after 1.85 s
[10:24:55] Starting 'watch'...
[10:24:56] Finished 'watch' after 264 ms
[10:24:56] Starting 'serve'...
[10:24:56] Finished 'serve' after 87 ms
[10:24:56] Starting 'default'...
[10:24:56] Finished 'default' after 1.6 μs
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://10.11.11.26:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://10.11.11.26:3001
 ------------------------------------
[BS] Serving files from: ./demo
Terminate batch job (Y/N)?
```

when so when i run glup -v
```
D:\JqueryFormbuilder\formBuilder-master>gulp -v
[10:40:12] Requiring external module babel-register
[10:40:12] CLI version 3.9.1
[10:40:12] Local version 3.9.1
```

screenshot of the localhost
scrrenshtot

### PR DESCRIPTION
**Pull request by kevinchappell**
Resolves #443

### CODE REVIEW

**Comment by aromka** [comment]
Seems like it still injects styles for toggles (kc-toggle) ... used to overwrite that through css, now it shows default styles again, even when disableInjectedStyle is set to true

**Comment by kevinchappell** [comment]
@aromka is the toggle the only issue? Is this in formRender, formBuilder or both? this feature probably needs to be extended to formRender as I only remember doing it for formBuilder

**Comment by aromka** [comment]
Only seeing it in formBuilder right now, haven't checked formRender yet.

**Comment by kevinchappell** [comment]
So all styles disappear except toggle or it's not working at all?

**Comment by aromka** [comment]
It seems like some other styles are injected as well - see screenshot: https://image.prntscr.com/image/af89edfaac0142b59d4afdfbbc7bc16f.png

**Pull request merged**
