### PR TITLE
Cleanup and linting

### PR DESCRIPTION
**Pull request by ivuorinen**
Move ’use strict’ inside functions, add linting rules for global funcs, add yarn.lock to gitignore.

(Status: ✖ 2 problems (2 errors, 0 warnings))

### CODE REVIEW

**Comment by ankurk91** [comment]
yarn.lock  file should not be ignored.
Read more -
https://yarnpkg.com/en/docs/yarn-lock

**Comment by kevinchappell** [comment]
the yarn.lock change is my only hold-up on merging this PR, as far as I know it is required.

**Comment by ankurk91** [comment]
Squash and merge may help here to keep history clean -
https://github.com/blog/2141-squash-your-commits

**Comment by kevinchappell** [comment]
@ankurk91 done. Github does that for us

**Comment by kevinchappell** [comment]
Also just want to add that I really like the increased activity. I'm not able to manage the project as much as I would like so its great to see you guys stepping in, really appreciated.

**Pull request merged**
